"""Moving is_active to user table

Revision ID: 3af157d8ed34
Revises: 97d439e571a2
Create Date: 2023-07-07 17:27:11.483182

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '3af157d8ed34'
down_revision = '97d439e571a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('created_at', sa.DateTime(), nullable = True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable= True ))
    # ### end Alembic commands ###

    op.execute(
        '''
        UPDATE users SET created_at = Now() Where created_at is NULL
        '''
    )
    op.execute(
        '''
        UPDATE profiles SET created_at = Now() Where created_at is NULL
        '''
    )
    
     # Alter the column to make it non-nullable
    op.alter_column('users', 'created_at', nullable=False )
    op.alter_column('profiles', 'created_at', nullable=False )
    

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('profiles', 'created_at')
    # ### end Alembic commands ###
