"""Fixing the null value , added default value of today to old and for future default is datetime now and fixed enum

Revision ID: 4beea02664d6
Revises: 3af157d8ed34
Create Date: 2023-07-08 13:46:57.685408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4beea02664d6'
down_revision = '3af157d8ed34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
