"""Moving is_active to user table

Revision ID: 97d439e571a2
Revises: 9afb8e125ae6
Create Date: 2023-07-07 17:09:58.280167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d439e571a2'
down_revision = '9afb8e125ae6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
